/**
 * @package Picasa Album Uploader
 * @author Kenneth J. Brucker <ken@pumastudios.com>
 * @copyright 2010 Kenneth J. Brucker (email: ken@pumastudios.com)
 * 
 * This file is part of Picasa Album Uploader, a plugin for Wordpress.
 *
 * Picasa Album Uploader is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * Picasa Album Uploader is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with Picasa Album Uploader.  If not, see <http://www.gnu.org/licenses/>.
 **/

/**
 * Fixup the hidden <input> tags Picasa detects to create the upload stream of files.
 * This function based on example downloaded from Google.
 *
 * @params string Image size to be generated by Picasa for upload
 */

function chURL(psize){
	jQuery("input[type='hidden']").each(function()
	{
		this.name = this.name.replace(/size=.*/,"size="+psize);
	});
}

/**
 * Setup Ajax login inside the minibrowser
 **/
// jQuery(document).ready( function($) {
// 	$('#pau-login-form').submit(function(event){
// 		//Stop event, add loading pic...
// 		event.preventDefault();
// 		//FIXME -- Add progress wheel
// //		$('<div class="LoginWithAjax_Loading" id="LoginWithAjax_Loading"></div>').prependTo('#LoginWithAjax');
// 
// 		//Get login URL
// 		var url = $('#pau-login-form input[name="redirect_to"]').attr('value');
// 		
// 		//Get POST data
// 		var loginData = getPostData('#pau-login-form *[name]');
// 
// 		//Make Ajax Call for login
// 		$.post(url, loginData, function(data){
// 			if(data.result === true){
// 				//Login Successful - Extra stuff to do
// 				jQuery('body').addClass('logged-in');
// 			} else {
// 				if (jQuery('#pau-login-form-error').size() === 0) {
// 					jQuery('<span id="pau-login-form-error"></span>').appendTo('#pau-login-form');					
// 				}
// 				jQuery('#pau-login-form-error').text(data.error);
// 			}
// 		}, "json");
// 	});
// 	
// 	//Get all POSTable data from form.
// 	function getPostData(selector){
// 		var postData = {};
// 		$.each($(selector), function(index,el){
// 			el = $(el);
// 			postData[el.attr('name')] = el.attr('value');
// 		});
// 		return postData;
// 	}
// });